package org.omnifaces.showcase.viewhandler;

import static org.omnifaces.util.Faces.getInitParameter;

import java.io.IOException;

import javax.faces.FacesException;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseEvent;
import javax.faces.event.PhaseId;

import org.omnifaces.util.Callback;
import org.omnifaces.util.Events;
import org.omnifaces.viewhandler.NoAutoGeneratedIdViewHandler;
import org.omnifaces.viewhandler.NoAutoGeneratedIdViewHandler.NoAutoGeneratedIdResponseWriter;

@ManagedBean
public class NoAutoGeneratedIdViewHandlerBean {

	/**
	 * Normally, the {@link NoAutoGeneratedIdViewHandler} is supposed to be installed as <view-handler> in
	 * faces-config.xml. However, as this affects the entire site and we'd like to keep the showcase examples as
	 * simple as possible (without forcing to specify ID boilerplate everytime), here's a different way of installing
	 * it on only a per-request basis.
	 *
	 * This is NOT the recommended approach. This is just done so for demo purposes.
	 */
	public void installResponseWriter() {
		Events.subscribeToRequestBeforePhase(PhaseId.RENDER_RESPONSE, new Callback.WithArgument<PhaseEvent>() {
			@Override
			public void invoke(PhaseEvent event) {
				FacesContext context = event.getFacesContext();
				ExternalContext ec = context.getExternalContext();
				ec.setResponseBufferSize(Integer.valueOf(getInitParameter("javax.faces.FACELETS_BUFFER_SIZE")));
				ec.setResponseContentType("text/html");
				ec.setResponseCharacterEncoding("UTF-8");

				try {
					context.setResponseWriter(new NoAutoGeneratedIdResponseWriter(
						context.getRenderKit().createResponseWriter(
							ec.getResponseOutputWriter(),
							ec.getResponseContentType(),
							ec.getResponseCharacterEncoding())));
				}
				catch (IOException e) {
					throw new FacesException(e);
				}
			}
		});
	}

}