package org.omnifaces.showcase.viewhandler;

import static org.omnifaces.util.Faces.getInitParameter;

import java.io.IOException;

import javax.faces.FacesException;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseEvent;
import javax.faces.event.PhaseId;

import org.omnifaces.util.Callback;
import org.omnifaces.util.Events;
import org.omnifaces.viewhandler.NoAutoGeneratedIdViewHandler.NoAutoGeneratedIdResponseWriter;

@ManagedBean
public class NoAutoGeneratedResponseWriterBean {

	public void installWriter() {
		Events.subscribeToRequestBeforePhase(PhaseId.RENDER_RESPONSE, new Callback.WithArgument<PhaseEvent>() {
			@Override
			public void invoke(PhaseEvent event) {
				FacesContext context = event.getFacesContext();
				ExternalContext externalContext = context.getExternalContext();
				externalContext.setResponseBufferSize(Integer.valueOf(getInitParameter("javax.faces.FACELETS_BUFFER_SIZE")));

				try {
					context.setResponseWriter(new NoAutoGeneratedIdResponseWriter(
						context.getRenderKit().createResponseWriter(
							externalContext.getResponseOutputWriter(),
							externalContext.getResponseContentType(),
							externalContext.getResponseCharacterEncoding())));
				}
				catch (IOException e) {
					throw new FacesException(e);
				}
			}
		});
	}

}